siteTitle = "Blog by Rion Daniel Gull"
siteDescr = "I love life, liberty, and the fruits of the free market."
siteAuthor = "Rion Daniel Gull"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = '/blog'
